version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
    

  client:
    build: ./client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - server
