version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
      - DB_URL=mongodb://mongodb:27017/thesis  
    depends_on:
      - mongodb
    
  client:
    build: ./client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - server

  mongodb:
      image: mongo:latest
      ports:
        - "27017:27017"
      volumes:
        - mongodb_data:/data/db
      environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=password1234

volumes:
  mongodb_data: